### ISSUE TITLE
 require is not defined

### ISSUE THREAD

**Issue by marcotruffat** [wobsoriano/vue-winbox#16]
I'm trying to use this component in a Vue3 project but no matter what, I keep getting this error.
I created a Vue project with Vite, and it works great there. It seems like it only works with Vite?

`Uncaught ReferenceError: require is not defined
    at eval (winbox.bundle.min.js:2:1)
    at ./node_modules/winbox/dist/winbox.bundle.min.js (chunk-vendors.js:2348:1)
    at __webpack_require__ (app.js:2854:33)
    at fn (app.js:3110:21)
    at eval (index.mjs:7:64)
    at ./node_modules/vue-winbox/dist/index.mjs (chunk-vendors.js:2315:1)
    at __webpack_require__ (app.js:2854:33)
    at fn (app.js:3110:21)
    at eval (main.js:22:69)
    at ./src/main.js (app.js:394:1)`

PS: I managed to solve this error by removing 'type: "modules"' from the winbox package.json, but it's a temporary solution. I'd like to know if there is a definitive solution.

**Comment by wobsoriano** [comment]
Are you using webpack/vue-cli?

**Comment by wobsoriano** [comment]
Check [this](https://github.com/nextapps-de/winbox/issues/25) out. If none of the comments fixes your issue, you can patch winbox locally using [patch-package](https://github.com/ds300/patch-package) and remove `"type": "modules"` in its `package.json` file.
